# Generated by Django 4.2.5 on 2023-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoon',
            name='char',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
