# Generated by Django 4.2.5 on 2024-09-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='about',
            new_name='Comments',
        ),
    ]
